version: '3'

services:
  backend:
    build:
      context: django
    command: sh -c "python manage.py collectstatic --no-input && gunicorn core.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
#    volumes:
#      - /var/www/static/:/var/www/static/
  frontend:
    build:
      context: react/blogapi
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
#      - /var/www/static/:/var/www/static/
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
